# Generated by Django 6.1.2 on 2026-10-07 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('shift', models.PositiveSmallIntegerField(choices=[(1, 'Tura 1'), (2, 'Tura 2')], default=1)),
                ('start_from', models.DateField()),
                ('inactive_from', models.DateField(blank=True, null=True)),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=40)),
            ],
            options={
                'ordering': ['section__order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=40)),
                ('bg', models.CharField(default='#f0ece3', max_length=9)),
                ('color', models.CharField(default='#5a5040', max_length=9)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('username', models.CharField(max_length=150)),
                ('action', models.CharField(choices=[('create', 'Adaugare'), ('update', 'Modificare'), ('delete', 'Stergere'), ('login', 'Autentificare'), ('export', 'Export')], max_length=10)),
                ('target', models.CharField(max_length=20)),
                ('summary', models.CharField(max_length=300)),
                ('before', models.CharField(blank=True, max_length=200)),
                ('after', models.CharField(blank=True, max_length=200)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pontaj.employee')),
            ],
            options={
                'ordering': ['-when'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='pontaj.section'),
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('start_h', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('end_h', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('code', models.CharField(blank=True, choices=[('SP', 'SP — 1 tura'), ('SP0.5', 'SP½ — ½ tura'), ('SP+', 'SP+ — 1.5 ture'), ('CO', 'CO — Concediu'), ('CM', 'CM — Medical'), ('OFF', 'OFF — Liber'), ('LP', 'LP — Liber cu plata'), ('LFP', 'LFP — Liber fara plata')], max_length=6)),
                ('approved', models.BooleanField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='pontaj.employee')),
            ],
            options={
                'indexes': [models.Index(fields=['day'], name='pontaj_entr_day_bfbe81_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'day'), name='one_entry_per_day')],
            },
        ),
        migrations.CreateModel(
            name='SummerBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Prima zi a lunii')),
                ('code', models.CharField(choices=[('SP', 'SP'), ('SP0.5', 'SP0.5'), ('SP+', 'SP+')], max_length=6)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='pontaj.employee')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('employee', 'month'), name='one_bonus_per_month')],
            },
        ),
    ]
